version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    restart: always
    volumes:
      - ./:/usr/src/app
    ports:
      - "3000:3000"
      - "4000:4000"
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    command: --replSet rs0 --bind_ip_all
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
      - "28017:28017"

  